services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    env_file:
      - ./.env
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

  backend:
    build: ./backend
    container_name: api
    env_file:
      - ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8000:80
    volumes:
      - ./backend:/app
    depends_on:
      - minio
      - mongodb

volumes:
  mongo:
